import { cn } from "../lib/cn";

const styles = {
  "auto-action": "w-auto",
  "number-input": "number-spinner-hidden",
  "progress-ring-background": "[background:conic-gradient(var(--color-brand)_var(--progress),rgb(245_255_252/13%)_0)]",
  "intro-eyebrow": "text-on-brand/80",
  screen: "screen-safe mx-auto w-full max-w-[680px] px-4 max-xs:px-3 sm:px-6",
  "loading-screen": "min-h-[70vh] place-items-center",
  loader: "size-[25px] animate-loader rounded-full border-2 border-line border-t-brand",
  notice: "sticky top-[max(10px,var(--tg-content-safe-area-inset-top,0px))] z-12 mb-3.5 grid w-full grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2.5 rounded-2xl border p-3 text-left text-small font-semibold leading-[1.4] shadow-[0_12px_30px_rgb(0_0_0/28%)] animate-notice-in [&>span]:min-w-0",
  "notice-error": "border-danger/30 bg-[#211315] text-[#ffb7bb]",
  "notice-success": "border-positive/30 bg-[#11201c] text-ink-soft",
  "notice-mark": "grid size-8 place-items-center rounded-[10px]",
  "notice-mark-error": "bg-danger-soft text-danger",
  "notice-mark-success": "bg-positive text-on-brand",
  "notice-close": "grid size-[42px] place-items-center rounded-[10px] bg-transparent p-0 text-muted hover:bg-white/5 hover:text-ink",
  "workspace-tabs": "mb-5 flex gap-[5px] rounded-[18px] bg-surface p-[5px]",
  "workspace-tab": "inline-flex min-h-[58px] min-w-0 flex-1 flex-col items-center justify-center gap-[3px] whitespace-nowrap rounded-control px-[5px] py-[7px] text-caption font-bold text-muted transition-colors hover:bg-surface-soft hover:text-brand aria-pressed:bg-brand aria-pressed:text-on-brand",
  "tab-content": "min-w-0",
  eyebrow: "mb-[5px] text-caption font-extrabold leading-[1.25] tracking-[.13em] text-brand",
  overline: "mb-[5px] text-caption font-extrabold leading-[1.25] tracking-[.11em] text-muted",
  muted: "m-0 text-body leading-[1.5] text-muted",

  "customer-dashboard": "mx-auto grid w-full max-w-[500px] gap-[22px]",
  "loyalty-summary-grid": "grid grid-cols-2 grid-rows-[repeat(2,156px)] gap-2.5 max-xs:grid-rows-[repeat(2,148px)] max-xs:gap-2",
  "loyalty-tile": "grid overflow-hidden rounded-card p-[17px] text-left max-xs:rounded-panel max-xs:p-3.5 [&_p]:m-0 [&_p]:text-body [&_p]:font-medium [&_strong]:block [&_strong]:text-[clamp(29px,8vw,40px)] [&_strong]:font-black [&_strong]:leading-[.95] [&_strong]:tracking-[-.055em] [&_strong]:tabular-nums max-xs:[&_strong]:text-[29px] [&_small]:text-caption [&_small]:leading-[1.35]",
  "points-tile": "col-start-1 row-start-1 content-between bg-tile text-on-tile [&_p]:text-on-tile [&_strong]:text-on-tile",
  "tile-title-row": "flex items-center justify-between gap-2",
  "cashback-tile": "col-start-2 row-span-2 row-start-1 grid-rows-[minmax(0,1fr)_auto] items-stretch bg-brand text-on-brand transition hover:-translate-y-px hover:saturate-[1.04]",
  "cashback-code-mark": "relative block aspect-square w-full max-w-[104px] self-center justify-self-center rounded-panel border-[3px] border-current text-on-brand max-xs:max-w-[88px] max-xs:rounded-[17px] [&>i]:absolute [&>i]:size-6 [&>i]:rounded-md [&>i]:border-[3px] [&>i]:border-current [&>i]:after:absolute [&>i]:after:inset-[5px] [&>i]:after:rounded-sm [&>i]:after:bg-current [&>i]:after:content-[''] max-xs:[&>i]:size-[21px] [&>i:nth-child(1)]:left-2.5 [&>i:nth-child(1)]:top-2.5 [&>i:nth-child(2)]:right-2.5 [&>i:nth-child(2)]:top-2.5 [&>i:nth-child(3)]:bottom-2.5 [&>i:nth-child(3)]:left-2.5 [&>span]:absolute [&>span]:bottom-[9px] [&>span]:right-[9px] [&>span]:grid [&>span]:size-[35px] [&>span]:place-items-center [&>span]:rounded-full [&>span]:bg-on-brand [&>span]:text-brand",
  "cashback-copy": "grid content-end gap-1 [&_small]:font-bold [&_small]:text-on-brand/70 [&_strong]:text-[clamp(34px,9vw,44px)] [&_strong]:text-on-brand [&_em]:mt-[5px] [&_em]:inline-flex [&_em]:items-center [&_em]:gap-1.5 [&_em]:text-small [&_em]:font-bold [&_em]:not-italic [&_em]:text-on-brand",
  "program-tile": "col-start-1 row-start-2 grid grid-rows-[1fr_auto] items-stretch gap-[9px] overflow-hidden rounded-card bg-tile p-[17px] text-left text-on-tile transition hover:-translate-y-px hover:bg-[#18332e] max-xs:rounded-panel max-xs:p-3.5 [&>i]:grid [&>i]:size-[42px] [&>i]:place-items-center [&>i]:rounded-full [&>i]:bg-brand [&>i]:not-italic [&>i]:text-on-brand max-xs:[&>i]:size-[38px]",
  "program-copy": "grid content-start gap-[7px] [&_strong]:text-[clamp(17px,4.8vw,22px)] [&_strong]:font-bold [&_strong]:leading-[1.08] [&_strong]:tracking-[-.035em] [&_strong]:text-on-tile",
  "benefit-carousel": "scrollbar-hidden -mr-4 flex snap-x snap-mandatory gap-3 overflow-x-auto py-px pr-4 pb-[5px] [scrollbar-width:none] [-webkit-overflow-scrolling:touch] max-xs:-mr-3 max-xs:pr-3 sm:mr-0 sm:pr-0",
  "benefit-card": "grid min-h-[188px] min-w-[min(86vw,340px)] flex-[0_0_min(86vw,340px)] snap-start rounded-card text-left sm:min-w-[340px] sm:basis-[340px]",
  "benefit-progress-card": "content-start gap-[15px] bg-tile p-5 text-on-tile transition hover:-translate-y-px hover:bg-[#18332e]",
  "benefit-progress-heading": "flex items-center justify-between gap-2.5 [&_p]:m-0 [&_p]:max-w-[270px] [&_p]:text-body [&_p]:font-bold [&_p]:leading-[1.2] [&_p]:text-on-tile",
  "benefit-progress-body": "grid grid-cols-[80px_minmax(0,1fr)] items-center gap-4 max-xs:grid-cols-[72px_minmax(0,1fr)] max-xs:gap-3 [&>div:last-child]:grid [&>div:last-child]:gap-[5px] [&>div:last-child>strong]:text-body [&>div:last-child>strong]:font-bold [&>div:last-child>strong]:leading-[1.2] [&>div:last-child>strong]:tracking-[-.025em] [&>div:last-child>strong]:text-on-tile [&>div:last-child>small]:text-caption [&>div:last-child>small]:leading-[1.35] [&>div:last-child>small]:text-on-tile/60",
  "progress-ring": "grid size-20 place-items-center rounded-full max-xs:size-[72px] [&>div]:grid [&>div]:size-16 [&>div]:place-items-center [&>div]:content-center [&>div]:gap-[3px] [&>div]:rounded-full [&>div]:bg-tile [&>div]:text-center max-xs:[&>div]:size-[58px] [&_strong]:grid [&_strong]:place-items-center [&_strong]:text-subtitle [&_strong]:font-extrabold [&_strong]:leading-none [&_strong]:tracking-[-.06em] [&_strong]:text-brand [&_small]:mt-[5px] [&_small]:text-caption [&_small]:font-bold [&_small]:uppercase [&_small]:tracking-[.07em] [&_small]:text-on-tile/50",
  "birthday-benefit-card": "relative grid grid-cols-[minmax(0,1fr)_112px] items-center gap-1 overflow-hidden bg-brand-soft p-5 text-ink [&>div]:relative [&>div]:z-1 [&>div]:grid [&>div]:content-center [&>div]:gap-1.5 [&_p]:m-0 [&_p]:text-body [&_p]:font-bold [&_p]:leading-[1.2] [&_p]:text-brand-dark [&_strong]:text-xl [&_strong]:font-black [&_strong]:leading-[1.05] [&_strong]:tracking-[-.035em] [&_small]:text-caption [&_small]:leading-[1.35] [&_small]:text-muted [&_img]:w-[142px] [&_img]:max-w-none [&_img]:self-center [&_img]:justify-self-end [&_img]:translate-x-[21px] [&_img]:translate-y-[5px]",
  "birthday-benefit-active": "bg-[#176a5c]",
  "customer-utility-row": "grid grid-cols-[minmax(0,1fr)_42px] gap-2 [&>button]:flex [&>button]:min-h-14 [&>button]:items-center [&>button]:justify-between [&>button]:gap-[9px] [&>button]:rounded-2xl [&>button]:bg-surface [&>button]:px-3.5 [&>button]:py-[11px] [&>button]:text-left [&>button]:text-small [&>button]:font-bold [&>button]:text-ink-soft [&>button]:transition-colors [&>button]:hover:bg-brand-soft [&>button>span]:inline-flex [&>button>span]:min-w-0 [&>button>span]:items-center [&>button>span]:gap-2 [&>button>svg]:text-brand",
  "profile-utility-button": "grid! w-[42px]! place-items-center! p-0! bg-brand-soft! text-brand-dark!",
  "customer-member-note": "-mt-2.5 mx-[3px] mb-0 text-caption text-muted",

  "primary-action": "inline-flex min-h-[54px] w-full items-center justify-center gap-2 rounded-2xl bg-brand px-4 py-[13px] text-body font-bold text-on-brand transition hover:-translate-y-px hover:bg-brand-dark disabled:opacity-50",
  "secondary-action": "inline-flex min-h-[54px] items-center justify-center gap-2 rounded-2xl bg-brand-soft px-4 py-[13px] text-body font-bold text-ink-soft transition-colors hover:bg-surface-tint",
  form: "grid gap-[13px] [&_label]:relative [&_label]:grid [&_label]:gap-[7px] [&_label]:text-small [&_label]:font-bold [&_label]:text-ink-soft",
  "form-grid": "grid grid-cols-1 gap-[11px] sm:grid-cols-2",
  "form-control": "min-h-[50px] w-full rounded-control border-0 bg-[#0d0f0e] px-[13px] py-[11px] text-ink caret-brand shadow-[inset_0_0_0_1px_var(--color-line)] outline-none transition placeholder:text-muted focus:bg-[#101312] focus:shadow-[inset_0_0_0_2px_var(--color-brand)]",
  compact: "mt-3.5",
  "split-actions": "grid grid-cols-[1fr_1.15fr] gap-2",
  check: "grid! grid-cols-[18px_minmax(0,1fr)]! items-start! text-small! font-semibold! leading-[1.45]! text-muted! [&_input]:mt-px [&_input]:size-4 [&_input]:min-h-4 [&_input]:bg-transparent [&_input]:p-0 [&_input]:shadow-none [&_input]:accent-brand",
  "icon-button": "inline-grid size-11 shrink-0 place-items-center rounded-control bg-brand-soft p-0 text-brand-dark hover:bg-surface-tint",
  icon: "shrink-0",
  money: "inline-flex items-baseline gap-[.2em] whitespace-nowrap",
  "currency-symbol": "currency-mask inline-block size-[.78em] shrink-0 bg-current",

  onboarding: "grid gap-3 sm:grid-cols-[.84fr_1.16fr] sm:items-start",
  "onboarding-intro": "rounded-[24px] bg-brand p-6 text-on-brand sm:min-h-full [&_.eyebrow]:text-on-brand/80 [&_h1]:m-0 [&_h1]:text-[clamp(30px,8vw,42px)] [&_h1]:font-bold [&_h1]:leading-[.95] [&_h1]:tracking-[-.07em] [&_h1]:text-on-brand [&>p:last-of-type]:mt-[13px] [&>p:last-of-type]:max-w-[390px] [&>p:last-of-type]:text-body [&>p:last-of-type]:leading-[1.5] [&>p:last-of-type]:text-on-brand/80",
  "onboarding-symbol": "mb-[17px] grid size-10 place-items-center rounded-[11px] bg-on-brand/10 text-on-brand/90",
  "onboarding-perks": "mt-[18px] flex flex-wrap gap-1.5 [&_span]:rounded-full [&_span]:border [&_span]:border-on-brand/20 [&_span]:bg-on-brand/10 [&_span]:px-2 [&_span]:py-1.5 [&_span]:text-caption [&_span]:text-on-brand/80 [&_b]:text-on-brand",
  "onboarding-form": "rounded-[24px] bg-surface p-5",
  "onboarding-steps": "mb-5 grid grid-cols-2 gap-2 [&_span]:inline-flex [&_span]:items-center [&_span]:gap-1.5 [&_span]:text-caption [&_span]:font-bold [&_span]:text-muted [&_i]:grid [&_i]:size-[19px] [&_i]:place-items-center [&_i]:rounded-full [&_i]:border [&_i]:border-line [&_i]:text-caption [&_i]:not-italic",
  "onboarding-step-active": "text-brand! [&_i]:border-brand! [&_i]:bg-brand! [&_i]:text-on-brand!",
  "onboarding-step": "grid gap-[15px] [&_h2]:m-0 [&_h2]:text-title [&_h2]:font-bold [&_h2]:tracking-[-.045em] [&_h2]:text-ink [&_p:not([data-overline])]:mt-[7px] [&_p:not([data-overline])]:text-small [&_p:not([data-overline])]:leading-[1.5] [&_p:not([data-overline])]:text-muted",

  "sales-workspace": "grid w-full min-w-0 gap-3.5",
  "owner-workspace": "grid w-full min-w-0 gap-3.5",
  "workspace-heading": "px-px pt-[5px] pb-0.5 [&_h1]:m-0 [&_h1]:text-[clamp(26px,6.7vw,34px)] [&_h1]:font-bold [&_h1]:leading-none [&_h1]:tracking-[-.07em] [&_h1]:text-ink [&>p:last-child]:mt-[9px] [&>p:last-child]:max-w-[500px] [&>p:last-child]:text-small [&>p:last-child]:leading-[1.5] [&>p:last-child]:text-muted",
  "sale-composer": "grid w-full min-w-0 gap-3.5 rounded-panel border border-line bg-surface p-[18px]",
  "sale-primary-fields": "grid gap-[15px]",
  "sale-section-heading": "grid grid-cols-[28px_minmax(0,1fr)] items-start gap-[9px] [&>span]:grid [&>span]:size-7 [&>span]:place-items-center [&>span]:rounded-[9px] [&>span]:bg-brand-soft [&>span]:text-small [&>span]:font-extrabold [&>span]:text-brand [&_h2]:m-0 [&_h2]:text-subtitle [&_h2]:font-bold [&_h2]:tracking-[-.035em] [&_h2]:text-ink [&_p]:mt-1 [&_p]:text-small [&_p]:leading-[1.4] [&_p]:text-muted",
  "sale-input-grid": "grid w-full min-w-0 grid-cols-1 gap-[11px] sm:grid-cols-2",
  "sale-field": "grid min-w-0 gap-[7px] text-small font-bold text-ink-soft [&>span:first-child]:pl-0.5 [&>span:first-child]:text-caption [&>span:first-child]:text-muted",
  "sale-control": "relative block w-full min-w-0 [&>svg]:pointer-events-none [&>svg]:absolute [&>svg]:left-[15px] [&>svg]:top-1/2 [&>svg]:z-1 [&>svg]:-translate-y-1/2 [&>svg]:text-brand [&_input]:block [&_input]:min-h-[58px] [&_input]:w-full [&_input]:min-w-0 [&_input]:appearance-none [&_input]:rounded-[18px] [&_input]:border-0 [&_input]:bg-[#090b0a] [&_input]:py-[13px] [&_input]:pr-[45px] [&_input]:pl-[47px] [&_input]:text-subtitle [&_input]:font-bold [&_input]:tabular-nums [&_input]:text-ink [&_input]:caret-brand [&_input]:shadow-[inset_0_0_0_1px_var(--color-line)] [&_input]:outline-0 [&_input]:transition [&_input]:placeholder:font-medium [&_input]:placeholder:text-[#58615f] [&_input]:focus:bg-[#0d100f] [&_input]:focus:shadow-[inset_0_0_0_2px_var(--color-brand),0_0_0_4px_rgb(2_193_159/10%)]",
  "sale-control-found": "[&_input]:shadow-[inset_0_0_0_2px_var(--color-brand)]",
  "field-loader": "absolute right-[22px] top-1/2 size-4 -translate-y-1/2 animate-loader rounded-full border-2 border-line border-t-brand",
  "field-status": "absolute right-[15px] top-1/2 grid size-[25px] -translate-y-1/2 place-items-center rounded-full bg-brand text-on-brand",
  "input-suffix": "pointer-events-none absolute right-[18px] top-1/2 -translate-y-1/2 text-brand [&_span]:size-[13px]",
  "customer-lookup-error": "col-span-full -mt-0.5 mx-0.5 flex items-center gap-[7px] text-caption leading-[1.35] text-danger",
  "identified-customer": "col-span-full grid grid-cols-[auto_minmax(0,1fr)] items-center gap-2.5 rounded-[18px] border border-brand/30 bg-brand/10 p-[13px] animate-customer-found [&_dl]:col-span-full [&_dl]:mt-0.5 [&_dl]:grid [&_dl]:grid-cols-2 [&_dl]:gap-[7px] [&_dl_div]:flex [&_dl_div]:items-baseline [&_dl_div]:justify-between [&_dl_div]:gap-2 [&_dl_div]:rounded-[11px] [&_dl_div]:bg-[#0c0f0e] [&_dl_div]:px-2.5 [&_dl_div]:py-[9px] [&_dt]:text-caption [&_dt]:text-muted [&_dd]:m-0 [&_dd]:text-small [&_dd]:font-extrabold [&_dd]:text-brand",
  "identified-avatar": "grid size-[42px] place-items-center rounded-control bg-brand text-body font-black text-on-brand",
  "identified-copy": "grid min-w-0 gap-0.5 [&_small]:text-caption [&_small]:font-black [&_small]:uppercase [&_small]:tracking-[.08em] [&_small]:text-brand [&_strong]:overflow-hidden [&_strong]:text-ellipsis [&_strong]:whitespace-nowrap [&_strong]:text-body [&_strong]:text-ink [&>span]:overflow-hidden [&>span]:text-ellipsis [&>span]:whitespace-nowrap [&>span]:text-caption [&>span]:text-muted",
  "product-picker": "rounded-2xl border border-line bg-[#101312] [&[open]>summary]:border-b [&[open]>summary]:border-line [&[open]>summary]:after:content-['−']",
  "product-picker-summary": "grid min-h-[60px] cursor-pointer grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-[9px] p-[11px] text-ink-soft after:col-start-3 after:text-subtitle after:font-medium after:text-brand after:content-['+'] [&>span:nth-child(2)]:grid [&>span:nth-child(2)]:min-w-0 [&>span:nth-child(2)]:gap-[3px] [&_strong]:text-small [&_strong]:font-bold [&_small]:text-caption [&_small]:text-muted [&>em]:col-start-2 [&>em]:text-caption [&>em]:font-semibold [&>em]:not-italic [&>em]:text-muted",
  "product-picker-icon": "grid size-[31px] place-items-center rounded-[9px] bg-brand-soft text-brand",
  "product-picker-content": "grid gap-[9px] p-[11px]",
  "selected-products": "grid list-none gap-[5px] p-0 m-0 [&_li]:flex [&_li]:items-center [&_li]:justify-between [&_li]:gap-2 [&_li]:rounded-[9px] [&_li]:bg-surface-tint [&_li]:px-[9px] [&_li]:py-2 [&_li]:text-ink-soft [&_li>span]:grid [&_li>span]:min-w-0 [&_li>span]:gap-0.5 [&_b]:overflow-hidden [&_b]:text-ellipsis [&_b]:whitespace-nowrap [&_b]:text-small [&_small]:text-caption [&_small]:text-muted [&_button]:grid [&_button]:size-[42px] [&_button]:shrink-0 [&_button]:place-items-center [&_button]:rounded-lg [&_button]:bg-surface-tint [&_button]:text-muted",
  "product-combobox": "overflow-hidden rounded-[15px] border border-line bg-[#0b0d0c]",
  "product-search": "relative block border-b border-line p-2 [&>svg]:pointer-events-none [&>svg]:absolute [&>svg]:left-[22px] [&>svg]:top-1/2 [&>svg]:z-1 [&>svg]:-translate-y-1/2 [&>svg]:text-brand [&_input]:pr-[42px] [&_input]:pl-[43px]",
  "product-dropdown": "max-h-[238px] overflow-y-auto overscroll-contain [scrollbar-color:var(--color-brand)_transparent]",
  "product-results": "m-0 list-none p-0 [&_li]:border-b [&_li]:border-line [&_li:last-child]:border-0 [&_button]:flex [&_button]:min-h-[54px] [&_button]:w-full [&_button]:items-center [&_button]:justify-between [&_button]:gap-2 [&_button]:bg-transparent [&_button]:px-3 [&_button]:py-2.5 [&_button]:text-left [&_button]:text-ink-soft [&_button]:transition-colors [&_button]:hover:bg-brand-soft [&_button_span]:grid [&_button_span]:min-w-0 [&_button_span]:gap-0.5 [&_b]:overflow-hidden [&_b]:text-ellipsis [&_b]:whitespace-nowrap [&_b]:text-small [&_small]:overflow-hidden [&_small]:text-ellipsis [&_small]:whitespace-nowrap [&_small]:text-caption [&_small]:text-muted [&_button>svg]:shrink-0 [&_button>svg]:text-brand",
  "product-empty": "px-3.5 py-[22px] text-center text-caption leading-[1.4] text-muted",
  "sale-submit": "mt-0.5",

  "owner-loading": "grid min-h-[180px] place-items-center gap-[11px] text-body text-muted",
  "modal-loader": "grid min-h-[180px] place-items-center gap-[11px] text-body text-muted",
  "owner-tabs": "grid grid-cols-3 gap-[5px] rounded-[18px] bg-surface p-[5px] [&_button]:inline-flex [&_button]:min-h-[58px] [&_button]:min-w-0 [&_button]:flex-col [&_button]:items-center [&_button]:justify-center [&_button]:gap-[3px] [&_button]:rounded-control [&_button]:bg-transparent [&_button]:px-[5px] [&_button]:py-[7px] [&_button]:text-caption [&_button]:font-bold [&_button]:text-muted [&_button]:transition-colors [&_button[aria-pressed=true]]:bg-brand [&_button[aria-pressed=true]]:text-on-brand",
  "owner-view": "grid gap-[13px]",
  "metrics-board": "grid grid-cols-2 gap-2 [&>div]:grid [&>div]:min-h-[122px] [&>div]:grid-cols-[auto_1fr] [&>div]:content-between [&>div]:items-center [&>div]:gap-2 [&>div]:rounded-[19px] [&>div]:border [&>div]:border-line [&>div]:bg-surface [&>div]:p-[15px] [&_small]:self-center [&_small]:text-caption [&_small]:text-muted [&_strong]:col-span-full [&_strong]:overflow-hidden [&_strong]:text-ellipsis [&_strong]:whitespace-nowrap [&_strong]:text-title [&_strong]:font-black [&_strong]:tracking-[-.04em] [&_strong]:text-ink",
  "metric-icon": "grid size-[35px] place-items-center rounded-[11px] bg-brand-soft text-brand",
  "owner-command-card": "rounded-panel border border-line bg-surface p-5 [&_h2]:m-0 [&_h2]:text-subtitle [&_h2]:font-bold [&_h2]:tracking-[-.04em] [&_h2]:text-ink [&_p:not([data-overline])]:mt-[5px] [&_p:not([data-overline])]:text-small [&_p:not([data-overline])]:leading-[1.45] [&_p:not([data-overline])]:text-muted",
  "owner-card": "rounded-panel border border-line bg-surface p-5",
  "command-actions": "mt-3.5 grid grid-cols-2 gap-[7px] [&_button]:grid [&_button]:min-h-[82px] [&_button]:justify-items-start [&_button]:gap-1.5 [&_button]:rounded-2xl [&_button]:border [&_button]:border-line [&_button]:bg-[#101312] [&_button]:p-[13px] [&_button]:text-left [&_button]:text-brand [&_button]:transition-colors [&_button]:hover:border-brand [&_button]:hover:bg-surface-soft [&_span]:text-small [&_span]:font-bold [&_span]:text-ink-soft [&_small]:text-caption [&_small]:font-bold [&_small]:text-muted",
  "command-team": "col-span-full grid-cols-[auto_1fr_auto]! min-h-12! items-center! justify-items-stretch! [&>svg:last-child]:text-muted",
  "view-heading": "mb-3.5 flex items-start justify-between gap-2.5 [&_h2]:m-0 [&_h2]:text-subtitle [&_h2]:font-bold [&_h2]:tracking-[-.04em] [&_h2]:text-ink [&_p:not([data-overline])]:mt-[5px] [&_p:not([data-overline])]:text-small [&_p:not([data-overline])]:leading-[1.45] [&_p:not([data-overline])]:text-muted",
  "soft-icon": "grid size-[35px] shrink-0 place-items-center rounded-[10px] bg-brand-soft text-brand",
  "search-form": "grid grid-cols-[minmax(0,1fr)_auto] gap-2 [&_.primary]:w-auto",
  "admin-search-field": "relative block min-w-0 [&>svg]:pointer-events-none [&>svg]:absolute [&>svg]:left-3.5 [&>svg]:top-1/2 [&>svg]:z-1 [&>svg]:-translate-y-1/2 [&>svg]:text-brand [&_input]:pl-[43px]",
  "customer-list": "mt-2.5 grid list-none p-0 [&_li]:border-b [&_li]:border-line",
  "customer-row": "grid w-full grid-cols-[minmax(0,1fr)_auto] gap-2 bg-transparent py-3 text-left text-ink-soft hover:text-brand [&>span]:grid [&>span]:min-w-0 [&>span]:gap-[3px] [&>span]:text-small [&>span]:font-bold [&_small]:overflow-hidden [&_small]:text-ellipsis [&_small]:whitespace-nowrap [&_small]:text-caption [&_small]:font-semibold [&_small]:text-muted [&_strong]:inline-flex [&_strong]:items-center [&_strong]:self-center [&_strong]:gap-1 [&_strong]:whitespace-nowrap [&_strong]:text-small [&_strong]:text-brand",
  "search-empty": "grid justify-items-center gap-1.5 px-2.5 pt-[27px] pb-2.5 text-center text-small text-muted [&>svg]:text-brand [&_strong]:text-body [&_strong]:text-ink-soft",
  "tier-editor": "mb-[15px] grid gap-2.5",
  "tier-config-card": "grid gap-[13px] rounded-[17px] border border-line bg-[#101312] p-3.5 [&>header]:flex [&>header]:items-center [&>header]:gap-2.5 [&>header>div]:grid [&>header>div]:gap-0.5 [&_header_strong]:text-small [&_header_strong]:text-ink [&_header_small]:text-caption [&_header_small]:text-muted",
  "tier-index": "grid size-[30px] shrink-0 place-items-center rounded-[10px] bg-brand text-small font-black text-on-brand",
  "tier-config-fields": "grid grid-cols-2 gap-[9px] [&_label]:relative [&_label]:grid [&_label]:gap-1.5 [&_label]:text-caption [&_label]:font-bold [&_label]:text-muted [&_input]:min-h-[50px] [&_input]:pr-[31px] [&_input]:text-small [&_em]:absolute [&_em]:right-[11px] [&_em]:bottom-[18px] [&_em]:text-caption [&_em]:not-italic [&_em]:text-brand [&_em_span]:size-[13px]",
  "team-link": "mt-[9px] flex w-full items-center justify-between gap-2.5 border-t border-line bg-transparent pt-[13px] text-small font-bold text-brand [&_span]:inline-flex [&_span]:items-center [&_span]:gap-[7px]",

  "modal-backdrop": "fixed inset-0 z-20 block overflow-hidden bg-canvas",
  "modal-sheet": "h-dvh w-screen max-h-none overflow-auto overscroll-contain bg-canvas text-ink animate-page-up",
  "modal-topline": "modal-header-safe sticky top-0 z-3 grid min-h-[74px] grid-cols-[42px_minmax(0,1fr)] items-center gap-[11px] border-b border-line bg-black/95 px-4 pb-3 backdrop-blur-[14px] [&>div]:grid [&>div]:min-w-0 [&>div]:content-center [&_h2]:m-0 [&_h2]:overflow-hidden [&_h2]:text-ellipsis [&_h2]:whitespace-nowrap [&_h2]:text-title [&_h2]:font-bold [&_h2]:leading-[1.08] [&_h2]:tracking-[-.035em] [&_h2]:text-ink",
  "modal-close": "size-10 bg-surface text-ink-soft hover:bg-surface-tint hover:text-ink",
  "modal-page-content": "modal-content-safe mx-auto min-h-[calc(100%-74px)] w-full max-w-[680px] px-4 pt-5 sm:px-6",
  "code-modal-copy": "mb-[17px] text-small leading-[1.45] text-muted",
  "code-loading": "grid min-h-[136px] place-items-center gap-2.5 text-small text-muted",
  "code-sheet": "grid gap-3.5 rounded-panel bg-brand-soft p-[18px] [&_p]:m-0 [&_p]:text-small [&_p]:leading-[1.45] [&_p]:text-muted [&_p_b]:text-ink-soft",
  "code-value": "grid grid-cols-[minmax(0,1fr)_44px] items-center gap-[9px] [&_output]:overflow-hidden [&_output]:text-clip [&_output]:whitespace-nowrap [&_output]:text-[clamp(33px,10vw,45px)] [&_output]:font-extrabold [&_output]:leading-none [&_output]:tracking-[.12em] [&_output]:tabular-nums [&_output]:text-brand",
  "copy-code": "grid size-11 place-items-center rounded-control bg-surface text-brand-dark transition-colors hover:bg-brand hover:text-on-brand",
  "copy-code-copied": "bg-brand text-on-brand",
  "text-action": "inline-flex justify-self-start items-center gap-[5px] bg-transparent p-0 text-small font-bold text-brand",
  "program-levels-view": "grid",
  "program-pane-heading": "mb-2.5 flex items-start justify-between gap-2.5 [&_h3]:m-0 [&_h3]:text-subtitle [&_h3]:font-bold [&_h3]:text-ink",
  "tier-status-list": "grid list-none gap-2.5 p-0",
  "tier-status-card": "grid gap-[13px] rounded-[18px] border border-line bg-surface-soft p-4 text-ink-soft [&>p]:m-0 [&>p]:text-small [&>p]:leading-[1.4] [&>p]:text-muted",
  "tier-status-current": "border-transparent bg-brand text-on-brand [&>p]:text-on-brand/70",
  "tier-status-reached": "border-brand/25",
  "tier-status-head": "flex items-start justify-between gap-3",
  "tier-status-name": "flex min-w-0 items-start gap-[9px] [&>span]:grid [&>span]:size-[27px] [&>span]:shrink-0 [&>span]:place-items-center [&>span]:rounded-[9px] [&>span]:bg-brand/15 [&>span]:text-brand [&>div]:grid [&>div]:min-w-0 [&>div]:gap-[3px] [&_strong]:text-body [&_strong]:font-black [&_strong]:uppercase [&_strong]:tracking-[-.02em] [&_strong]:text-ink [&_small]:text-caption [&_small]:text-muted",
  "tier-name-current": "[&>span]:bg-on-brand [&_strong]:text-on-brand [&_small]:text-on-brand/70",
  "tier-name-locked": "[&>span]:bg-[#151817] [&>span]:text-muted",
  "tier-reward": "grid min-h-[57px] min-w-[73px] shrink-0 place-items-center content-center gap-0.5 rounded-[13px] bg-[#090b0a] px-2.5 py-2 text-center text-on-tile [&_b]:text-body [&_b]:font-black [&_b]:leading-none [&_small]:text-caption [&_small]:font-bold [&_small]:uppercase [&_small]:text-on-tile/70",
  "tier-status-note": "inline-flex items-center gap-[7px] text-caption font-bold text-brand",
  "tier-note-current": "text-on-brand",
  "tier-unlock": "grid gap-2 [&>span]:text-small [&>span]:font-bold [&>span]:text-ink",
  "tier-progress-line": "h-[3px] overflow-hidden rounded-full bg-[#101312] [&_i]:block [&_i]:h-full [&_i]:rounded-[inherit] [&_i]:bg-brand [&_i]:transition-[width]",
  "balance-history-summary": "mb-6 grid grid-cols-[auto_minmax(0,1fr)] items-center gap-3.5 rounded-card bg-linear-to-br from-brand to-[#00a98d] p-5 text-on-brand shadow-[0_14px_36px_rgb(2_193_159/16%)] [&>div]:grid [&>div]:gap-[7px] [&>div>span]:text-small [&>div>span]:font-bold [&>div>span]:text-on-brand/70 [&_strong]:text-[34px] [&_strong]:font-black [&_strong]:leading-none [&_strong]:tracking-[-.045em] [&_strong]:text-on-brand",
  "balance-history-icon": "grid size-12 place-items-center rounded-[15px] bg-on-brand/15 text-on-brand",
  "transaction-history": "grid gap-3 [&>header]:flex [&>header]:items-center [&>header]:justify-between [&>header]:gap-3 [&>header]:px-0.5 [&_header_h3]:m-0 [&_header_h3]:text-subtitle [&_header_h3]:tracking-[-.025em] [&_header_h3]:text-ink [&_header_span]:grid [&_header_span]:h-[30px] [&_header_span]:min-w-[30px] [&_header_span]:place-items-center [&_header_span]:rounded-full [&_header_span]:bg-brand-soft [&_header_span]:px-2 [&_header_span]:text-caption [&_header_span]:font-extrabold [&_header_span]:text-brand",
  "transaction-list": "grid list-none gap-2.5 p-0 [&_li]:grid [&_li]:gap-3 [&_li]:rounded-[18px] [&_li]:border [&_li]:border-line [&_li]:bg-surface [&_li]:p-[15px]",
  "transaction-item-accrual": "border-brand/20!",
  "transaction-main": "grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3",
  "transaction-icon": "grid size-[42px] place-items-center rounded-[13px]",
  "transaction-icon-accrual": "bg-positive-soft text-positive",
  "transaction-icon-redemption": "bg-danger-soft text-danger",
  "transaction-copy": "grid min-w-0 content-center gap-1 [&_strong]:text-body [&_strong]:leading-[1.2] [&_strong]:text-ink [&_small]:text-caption [&_small]:leading-[1.3] [&_small]:text-muted",
  "transaction-amount": "self-center whitespace-nowrap text-subtitle font-extrabold not-italic tracking-[-.025em]",
  "transaction-amount-accrual": "text-positive",
  "transaction-amount-redemption": "text-danger",
  "transaction-balance": "flex items-baseline justify-between gap-3 border-t border-line pt-[11px] text-caption text-muted [&_b]:whitespace-nowrap [&_b]:text-small [&_b]:font-bold [&_b]:text-ink-soft",
  "purchase-timeline": "grid list-none gap-0 p-0 [&_li]:relative [&_li]:grid [&_li]:grid-cols-[13px_minmax(0,1fr)_auto] [&_li]:gap-[9px] [&_li]:pb-[15px] [&_li:last-child]:pb-0 [&_li:not(:last-child)]:before:absolute [&_li:not(:last-child)]:before:top-[13px] [&_li:not(:last-child)]:before:bottom-[-2px] [&_li:not(:last-child)]:before:left-[3px] [&_li:not(:last-child)]:before:w-px [&_li:not(:last-child)]:before:bg-line [&_li:not(:last-child)]:before:content-[''] [&_li>div]:grid [&_li>div]:gap-[3px] [&_small]:text-caption [&_small]:text-muted [&_strong]:text-body [&_strong]:text-ink-soft [&_em]:text-caption [&_em]:not-italic [&_em]:text-muted [&_li>b]:self-center [&_li>b]:whitespace-nowrap [&_li>b]:text-small [&_li>b]:text-positive",
  "purchase-dot": "relative z-1 mt-[5px] size-2 rounded-full border-2 border-brand bg-surface",
  "birthday-feature": "grid grid-cols-[auto_minmax(0,1fr)] items-center gap-[13px] rounded-[18px] bg-brand-soft p-4 [&>span]:grid [&>span]:size-[50px] [&>span]:place-items-center [&>span]:rounded-control [&>span]:bg-brand-soft [&>span]:text-brand [&>div]:grid [&>div]:gap-px [&_p]:m-0 [&_p]:text-caption [&_p]:font-semibold [&_p]:text-muted [&_strong]:text-[30px] [&_strong]:font-extrabold [&_strong]:leading-none [&_strong]:tracking-[-.07em] [&_strong]:text-brand-dark [&_small]:text-caption [&_small]:text-muted",
  "birthday-feature-active": "bg-positive-soft [&>span]:bg-brand [&>span]:text-on-brand",
  "birthday-explainer": "my-4 [&_h3]:m-0 [&_h3]:text-body [&_h3]:font-bold [&_h3]:text-ink-soft [&_p]:mt-1.5 [&_p]:text-small [&_p]:leading-[1.45] [&_p]:text-muted",
  "detail-list": "grid gap-0 [&_div]:flex [&_div]:items-baseline [&_div]:justify-between [&_div]:gap-3 [&_div]:border-b [&_div]:border-line [&_div]:px-px [&_div]:py-2.5 [&_div:last-child]:border-0 [&_dt]:text-small [&_dt]:text-muted [&_dd]:m-0 [&_dd]:text-right [&_dd]:text-small [&_dd]:font-bold [&_dd]:text-ink-soft",
  "account-modal-head": "flex items-center gap-[11px] rounded-[17px] bg-brand-soft p-[13px] [&>span]:grid [&>span]:size-[35px] [&>span]:shrink-0 [&>span]:place-items-center [&>span]:rounded-[10px] [&>span]:bg-brand [&>span]:text-body [&>span]:font-bold [&>span]:text-on-brand [&>div]:grid [&>div]:min-w-0 [&>div]:gap-0.5 [&_strong]:overflow-hidden [&_strong]:text-ellipsis [&_strong]:whitespace-nowrap [&_strong]:text-body [&_small]:text-caption [&_small]:text-muted",
  "account-details": "my-[13px]",
  "account-edit": "w-full",
  "receipt-customer": "flex items-center gap-[11px] rounded-[17px] bg-brand-soft p-[13px] [&>span]:grid [&>span]:size-[35px] [&>span]:shrink-0 [&>span]:place-items-center [&>span]:rounded-[10px] [&>span]:bg-brand [&>span]:text-body [&>span]:font-bold [&>span]:text-on-brand [&>div]:grid [&>div]:min-w-0 [&>div]:gap-0.5 [&_strong]:overflow-hidden [&_strong]:text-ellipsis [&_strong]:whitespace-nowrap [&_strong]:text-body [&_small]:text-caption [&_small]:text-muted",
  "receipt-totals": "my-3.5 grid gap-0 [&>div]:flex [&>div]:items-baseline [&>div]:justify-between [&>div]:gap-3 [&>div]:border-b [&>div]:border-line [&>div]:px-px [&>div]:py-2.5 [&_dt]:text-small [&_dt]:text-muted [&_dd]:m-0 [&_dd]:text-body [&_dd]:font-bold [&_dd]:text-ink",
  negative: "text-danger!",
  "receipt-total": "py-3! [&_dt]:text-body! [&_dt]:font-extrabold! [&_dt]:text-ink! [&_dd]:font-extrabold!",
  "receipt-cashback": "mt-[5px]! rounded-[10px]! border-0! bg-positive-soft! p-[11px]! [&_dt]:font-bold! [&_dt]:text-positive! [&_dd]:font-bold! [&_dd]:text-positive! [&_small]:text-caption [&_small]:text-muted",
  "modal-product-summary": "-mt-0.5 mb-[13px] flex items-center gap-[7px] text-small text-muted",
  "modal-warning": "mb-3.5 text-small leading-[1.4] text-danger",
  "success-hero": "grid justify-items-center px-2 pt-3 pb-6 text-center [&_h3]:m-0 [&_h3]:text-[27px] [&_h3]:font-extrabold [&_h3]:leading-[1.1] [&_h3]:tracking-[-.045em] [&_h3]:text-ink",
  "success-seal": "mb-[18px] grid size-[72px] place-items-center rounded-[23px] bg-linear-to-br from-brand to-[#00a98d] text-on-brand shadow-[0_14px_34px_rgb(2_193_159/22%)]",
  "success-kicker": "mb-2 text-caption font-extrabold tracking-[.09em] text-positive",
  "success-copy": "mx-auto mt-2.5 max-w-[390px] text-body leading-[1.55] text-muted",
  "success-summary": "mb-3 grid grid-cols-2 gap-2.5 [&_div]:grid [&_div]:min-w-0 [&_div]:gap-2 [&_div]:rounded-[18px] [&_div]:border [&_div]:border-line [&_div]:bg-surface [&_div]:px-[15px] [&_div]:py-[17px] [&_div:first-child]:border-brand/25 [&_div:first-child]:bg-positive-soft [&_div:first-child_dd]:text-positive [&_dt]:text-small [&_dt]:text-muted [&_dd]:m-0 [&_dd]:overflow-hidden [&_dd]:text-ellipsis [&_dd]:whitespace-nowrap [&_dd]:text-[clamp(20px,6vw,27px)] [&_dd]:font-extrabold [&_dd]:tracking-[-.045em] [&_dd]:text-ink",
  "success-note": "mb-[18px] flex items-center gap-2 rounded-control bg-surface-soft px-3.5 py-3 text-small text-ink-soft [&>svg]:shrink-0 [&>svg]:text-positive",
  "customer-detail-head": "flex items-center gap-[11px] rounded-[17px] bg-brand-soft p-[13px] [&>span]:grid [&>span]:size-[35px] [&>span]:shrink-0 [&>span]:place-items-center [&>span]:rounded-[10px] [&>span]:bg-brand [&>span]:text-body [&>span]:font-bold [&>span]:text-on-brand [&>div]:grid [&>div]:min-w-0 [&>div]:gap-0.5 [&_strong]:overflow-hidden [&_strong]:text-ellipsis [&_strong]:whitespace-nowrap [&_strong]:text-body [&_small]:text-caption [&_small]:text-muted",
  "customer-detail-metrics": "my-3 grid grid-cols-2 gap-2 max-xs:grid-cols-1 [&_span]:grid [&_span]:gap-1 [&_span]:rounded-[10px] [&_span]:bg-surface-soft [&_span]:p-2.5 [&_span]:text-caption [&_span]:text-muted [&_b]:text-small [&_b]:text-ink-soft",
  "modal-section-title": "mt-1 text-body text-ink-soft",
  "purchase-list": "grid list-none p-0 [&_li]:grid [&_li]:grid-cols-[75px_minmax(0,1fr)_auto] [&_li]:items-center [&_li]:gap-[9px] [&_li]:border-b [&_li]:border-line [&_li]:py-[11px] [&_li:last-child]:border-0 [&_strong]:text-small [&_strong]:text-ink-soft [&_em]:whitespace-nowrap [&_em]:text-small [&_em]:font-bold [&_em]:not-italic [&_em]:text-positive",
  "purchase-date": "text-caption text-muted",
  "empty-list": "block! text-small text-muted",
  "administrator-form": "my-[15px] grid grid-cols-[1fr_auto] gap-2",
  "administrator-list": "grid list-none p-0 [&_li]:grid [&_li]:grid-cols-[9px_minmax(0,1fr)_auto] [&_li]:items-center [&_li]:gap-2 [&_li]:border-b [&_li]:border-line [&_li]:px-px [&_li]:py-2.5 [&_div]:grid [&_div]:gap-0.5 [&_strong]:text-small [&_strong]:text-ink-soft [&_small]:text-caption [&_small]:text-muted [&_em]:text-caption [&_em]:font-bold [&_em]:not-italic [&_em]:text-positive",
  "role-dot-owner": "size-2 rounded-full bg-brand",
  "role-dot-sales": "size-2 rounded-full bg-positive",
  "empty-state": "grid justify-items-center px-3 pt-[30px] pb-4 text-center text-muted [&>span]:mb-[9px] [&>span]:grid [&>span]:size-[47px] [&>span]:place-items-center [&>span]:rounded-xl [&>span]:bg-brand-soft [&>span]:text-brand [&_h3]:mb-[5px] [&_h3]:text-body [&_h3]:text-ink-soft [&_p]:m-0 [&_p]:max-w-[250px] [&_p]:text-small [&_p]:leading-[1.45]",
  "compact-empty": "pt-2.5",
} as const;

export type UiClass = keyof typeof styles;

export function ui(...keys: Array<UiClass | false | null | undefined>): string {
  return cn(...keys.map((key) => (key ? styles[key] : key)));
}
